#include "memory_table.hpp"

uint8_t registerSize(uint8_t address)
{
    const uint8_t sizeInBytes[256] = {
        sizeof(MemoryTableDescription::Reg::Readings::GpioInput::value),            //  0
        0,                                                                          //  1
        0,                                                                          //  2
        0,                                                                          //  3
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch0::value),             //  4
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch0::value),             //  5
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch0::value),             //  6
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch0::value),             //  7
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch1::value),             //  8
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch1::value),             //  9
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch1::value),             // 10
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch1::value),             // 11
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch2::value),             // 12
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch2::value),             // 13
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch2::value),             // 14
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch2::value),             // 15
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch3::value),             // 16
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch3::value),             // 17
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch3::value),             // 18
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch3::value),             // 19
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch4::value),             // 20
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch4::value),             // 21
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch4::value),             // 22
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch4::value),             // 23
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch5::value),             // 24
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch5::value),             // 25
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch5::value),             // 26
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch5::value),             // 27
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch6::value),             // 28
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch6::value),             // 29
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch6::value),             // 30
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch6::value),             // 31
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch7::value),             // 32
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch7::value),             // 33
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch7::value),             // 34
        sizeof(MemoryTableDescription::Reg::Readings::Adc::Ch7::value),             // 35
        sizeof(MemoryTableDescription::Reg::Readings::Encoder0::value),             // 36
        sizeof(MemoryTableDescription::Reg::Readings::Encoder0::value),             // 37
        sizeof(MemoryTableDescription::Reg::Readings::Encoder0::value),             // 38
        sizeof(MemoryTableDescription::Reg::Readings::Encoder0::value),             // 39
        sizeof(MemoryTableDescription::Reg::Readings::Encoder1::value),             // 40
        sizeof(MemoryTableDescription::Reg::Readings::Encoder1::value),             // 41
        sizeof(MemoryTableDescription::Reg::Readings::Encoder1::value),             // 42
        sizeof(MemoryTableDescription::Reg::Readings::Encoder1::value),             // 43
        sizeof(MemoryTableDescription::Reg::Readings::Encoder2::value),             // 44
        sizeof(MemoryTableDescription::Reg::Readings::Encoder2::value),             // 45
        sizeof(MemoryTableDescription::Reg::Readings::Encoder2::value),             // 46
        sizeof(MemoryTableDescription::Reg::Readings::Encoder2::value),             // 47
        sizeof(MemoryTableDescription::Reg::Readings::Encoder3::value),             // 48
        sizeof(MemoryTableDescription::Reg::Readings::Encoder3::value),             // 49
        sizeof(MemoryTableDescription::Reg::Readings::Encoder3::value),             // 50
        sizeof(MemoryTableDescription::Reg::Readings::Encoder3::value),             // 51
        sizeof(MemoryTableDescription::Reg::Readings::Encoder4::value),             // 52
        sizeof(MemoryTableDescription::Reg::Readings::Encoder4::value),             // 53
        sizeof(MemoryTableDescription::Reg::Readings::Encoder4::value),             // 54
        sizeof(MemoryTableDescription::Reg::Readings::Encoder4::value),             // 55
        sizeof(MemoryTableDescription::Reg::Readings::Encoder5::value),             // 56
        sizeof(MemoryTableDescription::Reg::Readings::Encoder5::value),             // 57
        sizeof(MemoryTableDescription::Reg::Readings::Encoder5::value),             // 58
        sizeof(MemoryTableDescription::Reg::Readings::Encoder5::value),             // 59
        sizeof(MemoryTableDescription::Reg::Readings::Encoder6::value),             // 60
        sizeof(MemoryTableDescription::Reg::Readings::Encoder6::value),             // 61
        sizeof(MemoryTableDescription::Reg::Readings::Encoder6::value),             // 62
        sizeof(MemoryTableDescription::Reg::Readings::Encoder6::value),             // 63
        sizeof(MemoryTableDescription::Reg::Readings::Encoder7::value),             // 64
        sizeof(MemoryTableDescription::Reg::Readings::Encoder7::value),             // 65
        sizeof(MemoryTableDescription::Reg::Readings::Encoder7::value),             // 66
        sizeof(MemoryTableDescription::Reg::Readings::Encoder7::value),             // 67
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch0::value),           // 68
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch0::value),           // 69
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch0::value),           // 70
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch0::value),           // 71
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch1::value),           // 72
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch1::value),           // 73
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch1::value),           // 74
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch1::value),           // 75
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch2::value),           // 76
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch2::value),           // 77
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch2::value),           // 78
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch2::value),           // 79
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch3::value),           // 80
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch3::value),           // 81
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch3::value),           // 82
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch3::value),           // 83
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch4::value),           // 84
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch4::value),           // 85
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch4::value),           // 86
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch4::value),           // 87
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch5::value),           // 88
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch5::value),           // 89
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch5::value),           // 90
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch5::value),           // 91
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch6::value),           // 92
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch6::value),           // 93
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch6::value),           // 94
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch6::value),           // 95
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch7::value),           // 96
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch7::value),           // 97
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch7::value),           // 98
        sizeof(MemoryTableDescription::Reg::Action::PwmDuty::Ch7::value),           // 99
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch0::value),              // 100
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch0::value),              // 101
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch0::value),              // 102
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch0::value),              // 103
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch1::value),              // 104
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch1::value),              // 105
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch1::value),              // 106
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch1::value),              // 107
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch2::value),              // 108
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch2::value),              // 109
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch2::value),              // 110
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch2::value),              // 111
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch3::value),              // 112
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch3::value),              // 113
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch3::value),              // 114
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch3::value),              // 115
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch4::value),              // 116
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch4::value),              // 117
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch4::value),              // 118
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch4::value),              // 119
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch5::value),              // 120
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch5::value),              // 121
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch5::value),              // 122
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch5::value),              // 123
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch6::value),              // 124
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch6::value),              // 125
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch6::value),              // 126
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch6::value),              // 127
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch7::value),              // 128
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch7::value),              // 129
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch7::value),              // 130
        sizeof(MemoryTableDescription::Reg::Action::Dac::Ch7::value),              // 131
        sizeof(MemoryTableDescription::Reg::Action::GpioOutput::value),            // 132
        sizeof(MemoryTableDescription::Reg::Action::GpioOutput::value),            // 133
        0,                                                                         // 134
        0,                                                                         // 135
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Max::Ch0::value),   // 136
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Max::Ch1::value),   // 137
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Max::Ch2::value),   // 138
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Max::Ch3::value),   // 139
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Max::Ch4::value),   // 140
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Max::Ch5::value),   // 141
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Max::Ch6::value),   // 142
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Max::Ch7::value),   // 143
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Min::Ch0::value),   // 144
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Min::Ch1::value),   // 145
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Min::Ch2::value),   // 146
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Min::Ch3::value),   // 147
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Min::Ch4::value),   // 148
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Min::Ch5::value),   // 149
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Min::Ch6::value),   // 150
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Range::Min::Ch7::value),   // 151
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Mode::value),              // 152
        sizeof(MemoryTableDescription::Reg::Setup::Adc::Mode::value),              // 153
        sizeof(MemoryTableDescription::Reg::Setup::Encoder::Quadrature::value),    // 154
        sizeof(MemoryTableDescription::Reg::Setup::Encoder::Quadrature::value),    // 155
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch0::value),    // 156
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch0::value),    // 157
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch0::value),    // 158
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch0::value),    // 159
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch1::value),    // 160
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch1::value),  // 161
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch1::value),  // 162
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch1::value),  // 163
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch2::value),  // 164
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch2::value),  // 165
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch2::value),  // 166
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch2::value),  // 167
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch3::value),  // 168
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch3::value),  // 169
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch3::value),  // 170
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch3::value),  // 171
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch4::value),  // 172
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch4::value),  // 173
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch4::value),  // 174
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch4::value),  // 175
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch5::value),  // 176
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch5::value),  // 177
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch5::value),  // 178
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch5::value),  // 179
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch6::value),  // 180
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch6::value),  // 181
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch6::value),  // 182
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch6::value),  // 183
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch7::value),  // 184
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch7::value),  // 185
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch7::value),  // 186
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Frequency::Ch7::value),  // 187
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Config::Ch0::all),            // 188
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Config::Ch1::all),            // 189
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Config::Ch2::all),            // 190
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Config::Ch3::all),            // 191
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Config::Ch4::all),            // 192
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Config::Ch5::all),            // 193
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Config::Ch6::all),            // 194
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::Config::Ch7::all),            // 195
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch0),  // 196
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch0),  // 197
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch1),  // 198
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch1),  // 199
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch2),  // 200
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch2),  // 201
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch3),  // 202
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch3),  // 203
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch4),  // 204
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch4),  // 205
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch5),  // 206
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch5),  // 207
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch6),  // 208
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch6),  // 209
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch7),  // 210
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::FallingEdge::Ch7),  // 211
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch0),   // 212
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch0),   // 213
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch1),   // 214
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch1),   // 215
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch2),   // 216
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch2),   // 217
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch3),   // 218
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch3),   // 219
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch4),   // 220
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch4),   // 221
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch5),   // 222
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch5),   // 223
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch6),   // 224
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch6),   // 225
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch7),   // 226
        sizeof(MemoryTableDescription::Reg::Setup::Pwm::DeadTime::RisingEdge::Ch7),   // 227
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Max::Ch0::value),      // 228
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Max::Ch1::value),      // 229
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Max::Ch2::value),      // 230
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Max::Ch3::value),      // 231
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Max::Ch4::value),      // 232
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Max::Ch5::value),      // 233
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Max::Ch6::value),      // 234
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Max::Ch7::value),      // 235
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Min::Ch0::value),      // 236
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Min::Ch1::value),      // 237
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Min::Ch2::value),      // 238
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Min::Ch3::value),      // 239
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Min::Ch4::value),      // 240
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Min::Ch5::value),      // 241
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Min::Ch6::value),      // 242
        sizeof(MemoryTableDescription::Reg::Setup::Dac::Range::Min::Ch7::value),      // 243
        4,                                                                            // 244
        4,                                                                            // 245
        4,                                                                            // 246
        4,                                                                            // 247
        0,                                                                            // 248
        0,                                                                            // 249
        0,                                                                            // 250
        0,                                                                            // 251
        0,                                                                            // 252
        0,                                                                            // 253
        sizeof(MemoryTableDescription::Reg::Setup::BoardModel),                       // 254
        sizeof(MemoryTableDescription::Reg::Setup::WhoAmI),                           // 256
    };

    return sizeInBytes[address];
}

